#Todo (zack): Refactor the steps into separate jobs to optimize the build time
on:
  push:
    branches: [develop,SET-11-ci-cd-pipeline]
  pull_request:
    branches: [develop,SET-11-ci-cd-pipeline]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: 'npm' #A simple way to cache dependencies between workflows
       #I found a better an action that already supports firebase
#      - name: Install Firebase Suite
#        run: npm install -g firebase-tools
      - name: Install dependencies
        run: npm ci
      - name: Lint & Analyze
        run: npm run format && npm run lint
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist/se-poc
        env:
          SE_API_KEY: ${{ secrets.STAGE_API_KEY }}
          SE_AUTH_DOMAIN: ${{ secrets.STAGE_AUTH_DOMAIN }}
          SE_PROJECT_ID: ${{ secrets.STAGE_PROJECT_ID }}
          SE_STORAGE_BUCKET: ${{ secrets.STAGE_STORAGE_BUCKET }}
          SE_MESSAGING_SENDER_ID: ${{ secrets.STAGE_MESSAGING_SENDER_ID }}
          SE_APP_ID: ${{ secrets.STAGE_APP_ID }}
          SE_MEASUREMENT_ID: ${{ secrets.STAGE_MEASUREMENT_ID }}
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
<<<<<<< HEAD
          path: dist/dist/se-poc
=======
          path: ./dist/se-poc
>>>>>>> ae6af221e0560f0b349a1755b365e17f65301fbc
      - name: Deploy to Staging Env Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


